### ISSUE TITLE
Bug in `clean_maf`

### ISSUE THREAD

**Issue by vladimirsouza** [morinlab/GAMBLR.utils#16]
```
> clean_maf = cleanup_maf(maf_df = GAMBLR.data::sample_data$grch37$maf)
Error in `mutate()`:
ℹ In argument: `EXON = gsub("/.+", "", EXON)`.
Caused by error in `h()`:
! error in evaluating the argument 'x' in selecting a method for function 'gsub': object 'EXON' not found
```
The input MAF table may not have a EXON column. 
```
> maf <- GAMBLR.results::get_coding_ssm()
> any( names(maf) == "EXON" )
[1] FALSE
```
In `cleanup_maf` code:
```
> mutate(maf_df,EXON = gsub("/.+", "", EXON))
Error in `mutate()`:
ℹ In argument: `EXON = gsub("/.+", "", EXON)`.
Caused by error in `is.factor()`:
! object 'EXON' not found
```

**Comment by Kdreval** [comment]
The clean_maf is meant for use on the unreleased data. So the bundled maf is not the best use case here. Can you try passing here a maf that has all columns?

**Comment by vladimirsouza** [comment]
Yeah! Of course. Sorry, I forgot to use `basic_columns = FALSE`.
```
> maf <- GAMBLR.results::get_coding_ssm(basic_columns = FALSE)
> clean_maf = cleanup_maf(maf_df = maf)
Warning messages:
1: There was 1 warning in `mutate()`.
ℹ In argument: `CDS_position = as.numeric(as.character(CDS_position))`.
Caused by warning:
! NAs introduced by coercion 
2: There was 1 warning in `mutate()`.
ℹ In argument: `cDNA_position = as.numeric(as.character(cDNA_position))`.
Caused by warning:
! NAs introduced by coercion 
3: There was 1 warning in `mutate()`.
ℹ In argument: `Protein_position = as.numeric(as.character(Protein_position))`.
Caused by warning:
! NAs introduced by coercion 
```
The warning messages seem to be because there are NAs and this should be fine.

**Comment by vladimirsouza** [comment]
We should probably change the examples though, which uses the bundled data.
```
#' @examples
#'
#' clean_maf = cleanup_maf(maf_df = GAMBLR.data::sample_data$grch37$maf)
```
Would it be better to move this function to GAMBLR.results since it is exclusively for this package?

**Comment by Kdreval** [comment]
Yeah, this particular function might be better homed in the results package because of the intended use case of this. Thanks!

**Comment by vladimirsouza** [comment]
I think this is the same case with `annotate_maf_triplet`. It needs the `STRAND_VEP` column that is presented only in the restricted data. Should we migrate `annotate_maf_triplet` from GAMBLR.utils to GAMBLR.results as well?
```
> maf_triple <- annotate_maf_triplet(maf, all_SNVs = FALSE, "C", "T")
Error in annotate_maf_triplet(maf, all_SNVs = FALSE, "C", "T") : 
  STRAND_VEP column is not in the MAF
```

**Comment by vladimirsouza** [comment]
Solved in [this](https://github.com/morinlab/GAMBLR.results/pull/14) PR.
